devtools::install_version("umap", "0.2.7.0")
devtools::install_version("scales", "1.1.1")
devtools::install_version("MASS", "7.3-54")
devtools::install_version("RColorBrewer", "1.1-2")
devtools::install_version("colorRamps", "2.3")
devtools::install_version("vegan", "2.5-7")
devtools::install_version("igraph", "1.2.11")
devtools::install_version("entropy", "1.3.1")
devtools::install_version("jpeg", "0.1-9")
devtools::install_version("repr", "1.1.4")
devtools::install_version("dunn.test", "1.3.5")
devtools::install_version("vioplot", "0.3.7")
devtools::install_version("lsa", "0.73.2")
devtools::install_version("shape", "1.4.6")
devtools::install_version("gtools", "3.9.2")
devtools::install_version("pracma", "2.3.6")
devtools::install_version("fractaldim", "0.8-5")
devtools::install_github("swarm-lab/swaRm")
